create DATABASE IF NOT EXISTS XYZ;
USE XYZ;
CREATE TABLE IF NOT EXISTS EMPLOYEE (
	ID INT PRIMARY KEY,
    NAME VARCHAR(50),
    SALARY  FLOAT NOT NULL
);
INSERT INTO EMPLOYEE (ID, NAME, SALARY)
	VALUES
	(1 , "ADAM", 25000),
    (2, "BOB", 30000),
    (3, "CASEY", 40000)
    ;
SELECT * FROM EMPLOYEE;